{"author":{"id":"c2c697aab15a361aec94cc441a887c46130bd846efc1d890c49acaec05a0b8be"},"ops":[{"type":3,"timestamp":1594906149,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDY1OTQxMjIzOQ==","github-url":"https://github.com/MichaelMure/git-bug/issues/366#issuecomment-659412239"},"nonce":"8MOrlemWpLE9ipN4Gso/IioAem4=","message":"\u003e Hi, I am receiving the same panic: runtime error: index out of range [-1] on the repo that I used for testing in #360.\n\nI think it is related to https://github.com/MichaelMure/git-bug/pull/378 cause it works perfectly when you add a first issue on gitlab.\n\nBtw, there is any steps done about this gitlab gridge? \n\nI'll clone my other issue cause it is just a duplicate of this : https://github.com/MichaelMure/git-bug/issues/389","files":null},{"type":6,"timestamp":1594906156,"metadata":{"github-id":"MDE1OlVzZXJDb250ZW50RWRpdElzc3VlQ29tbWVudEVkaXQ6Mzg2MzA1NDQw"},"nonce":"vH0aparHs4Us1NKgqYfraLgH3Wc=","target":"a7e8fea65ac464fa0360a662dd61bcb7d9175cab46f5f70568b04636b8db3e63","message":"\u003e Hi, I am receiving the same panic: runtime error: index out of range [-1] on the repo that I used for testing in #360.\n\nI think it is related to https://github.com/MichaelMure/git-bug/pull/378 cause it works perfectly when you add a first issue on gitlab.\n\nBtw, there is any steps done about this gitlab gridge? \n\nI'll close my other issue cause it is just a duplicate of this : https://github.com/MichaelMure/git-bug/issues/389","files":null}]}