{"author":{"id":"a99b826294359757366d8d53a41dce5cf8e99657f3b1ce221b354e6a92dc7007"},"ops":[{"type":3,"timestamp":1619383466,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDgyNjM4NzI1Mg==","github-url":"https://github.com/MichaelMure/git-bug/issues/653#issuecomment-826387252"},"nonce":"Dd31CJuSrAWmrDwNozBR0QKGhzk=","message":"Reverting [this line](https://github.com/MichaelMure/git-bug/blob/master/bug/op_edit_comment.go#L38) back to `commentId = op.target` seems to fix the issue. But I'm not sure if this is the right way to solve the problem. [This discussion](https://github.com/MichaelMure/git-bug/pull/631#pullrequestreview-635388561)  seems to be related, maybe reverting the line was just forgotten?","files":null}]}