{"author":{"id":"c803539e034909e56c9c5c809058230d0e120d8fe2315f63b319a3b148517369"},"ops":[{"type":3,"timestamp":1572279510,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDU0NzAyNTA1Mg==","github-url":"https://github.com/MichaelMure/git-bug/issues/235#issuecomment-547025052"},"nonce":"N2KOyNA3V5GwirYWnxJ3Tl+mOHk=","message":"Ok great! I'll hold off on deleting the cache and try to spot any more bugs that incorrectly show up as open. Then I'll delete the cache and see if they show up as closed. I will report back.","files":null},{"type":3,"timestamp":1573667270,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDU1MzUyMjI4MA==","github-url":"https://github.com/MichaelMure/git-bug/issues/235#issuecomment-553522280"},"nonce":"r27RKj/aKndUH090RFcfGxKoX9w=","message":"Ok I got a situation where this happened again. Indeed deleting the cache seems to have fixed the stale status. However, I don't think the stale status was due to crash this time. I'm pretty sure that this happened after two pulls, with no local edits to the bug. Here is what I think the situation was:\n\nMachine A: \n* Create bug `d3c0372`\n* `git bug push`\nMachine B:\n* `git bug pull` -\u003e new bug `d3c0372`\n* `git bug termui` -\u003e verify I can see new bug, \"enter\" to see the detail page\nMachine A:\n* Close bug `d3c0372`\n* `git bug push`\nMachine B:\n* `git bug pull`\n* `git bug termui` -\u003e `d3c0372` shows \"open\"\n* \"enter\" on `d3c0372` -\u003e details page shows \"closed\"\n* `q` back to the main page -\u003e `d3c0372` is not longer listed with \"open\" bugs\n\nWhen I get a chance I will try to replicate this in a controlled setting and report back.","files":null},{"type":6,"timestamp":1573667295,"metadata":{"github-id":"MDE1OlVzZXJDb250ZW50RWRpdDMwODU0NDU5OQ=="},"nonce":"IuYwuhVWTx5REB6ykTcjfQ5bnFQ=","target":"dcf488473ea5dc71b6e251a2a9bc131487a820e6b3c4e051a7479b98ed7b0ff1","message":"Ok I got a situation where this happened again. Indeed deleting the cache seems to have fixed the stale status. However, I don't think the stale status was due to crash this time. I'm pretty sure that this happened after two pulls, with no local edits to the bug. Here is what I think the situation was:\n\nMachine A: \n* Create bug `d3c0372`\n* `git bug push`\n\nMachine B:\n* `git bug pull` -\u003e new bug `d3c0372`\n* `git bug termui` -\u003e verify I can see new bug, \"enter\" to see the detail page\n\nMachine A:\n* Close bug `d3c0372`\n* `git bug push`\n\nMachine B:\n* `git bug pull`\n* `git bug termui` -\u003e `d3c0372` shows \"open\"\n* \"enter\" on `d3c0372` -\u003e details page shows \"closed\"\n* `q` back to the main page -\u003e `d3c0372` is not longer listed with \"open\" bugs\n\nWhen I get a chance I will try to replicate this in a controlled setting and report back.","files":null}]}