{"author":{"id":"708ccc11728eda0dd404c8de33ac6b44bac2ffc95b2ffc6ea90ce98ccdb43935"},"ops":[{"type":3,"timestamp":1619194703,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDgyNTc2NzU3Ng==","github-url":"https://github.com/MichaelMure/git-bug/issues/642#issuecomment-825767576"},"nonce":"HNSeYmWYvA2XFdK1BrJ4/pUCal4=","message":"WTF :-D\n\nIn that case that should be easy to reproduce/debug but what I'm confused about is that our tests should protect against something as obvious.","files":null}]}